### ISSUE TITLE
Broken map

### ISSUE THREAD

**Issue by spektro** [DarwinNE/innuhs_pyramid#1]
Hi, I think I've found a bug when I tried to draw a map of the game world.

You can walk from the first room, where the torch is, indefinitely to the north. When you walk back once (to the south), you'll end in the room where the wooden girder is. Walk south again and you're in the front of the pyramid. If you walk north from there, you'll appear in the room where the sign is. One more step to the north and you're in the first room where the torch is.

There is also something very fishy when you walk in the east-west direction.

**Comment by DarwinNE** [comment]
Hi @spektro 
Indeed, the beginning of the game is meant to let the player loose the orientation.
There was the same behavior in the original version of the game by A. Torrelli. I think the idea was that it is easy to loose yourself in the desert :)
