### ISSUE TITLE
Extraneous Input In Game

### ISSUE THREAD

**Issue by cx** [DarwinNE/innuhs_pyramid#5]
User "Elia Spallanzani" on Atari Age reports that randomly, the user will type a valid command and the game will respond with "I don't understand".  To be clear, the game executes the command given, but also responds with "I don't understand".  Elia says that the game responds as if the "return" key was pressed an extra time after the typed command.

The user reported that this happened on the TI994A Italian version.  It is unknown whether this occurs in other versions, as I was unable to reproduce the issue.

More information in this post on Atari Age as well as subsequent posts:
https://atariage.com/forums/topic/319903-the-innuhs-pyramid/?do=findComment&comment=4826550

**Comment by cx** [comment]
This has been resolved in the latest TI build.  It was a bug in the TI keyboard routine, where the return key was auto-repeating.  The game was seeing extra return key presses if the return key was held down.

I will open a pull request with the fix.

**Comment by DarwinNE** [comment]
Thank you for the contribution!
